### ISSUE TITLE
API Enhancement | Result of trade

### ISSUE THREAD

**Issue by Zimon4eR** [CJcool06/SafeTrade-Releases#1]
Please add something so we can check if TradeEndEvent was called because of error (user has no money / last pokemon in team) or success.

**Comment by CJcool06** [comment]
TradeEndEvent holds a TradeResult in version 1.1.6 that indicates the result of the trade.

`public enum TradeResult {
    /**
     * The trade was successfully executed.
     */
    SUCCESS,

    /**
     * The trade failed due to an expected condition.
     */
    FAILURE,

    /**
     * The trade was ended due to an unexpected condition.
     */
    ERROR,

    /**
     * The trade was cancelled.
     */
    CANCELLED
}`
